[package]
name = "newlang"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
tests_generator_macro = { path = "tests_generator_macro" }
