__builtin_file_catch_assert_eq(assert_eq(2, 4)),
__builtin_file_catch_assert_eq(assert_eq(true, 1)),
__builtin_file_catch_assert_eq(assert_eq(fn(_()), 1)),
type(F),
__builtin_file_catch_assert_eq(assert_eq(F(), null)),
__builtin_file_catch_assert_eq(assert_eq(_, _)),
