import(lists),
=(l, list(2, 5, 6, "a", list(2, 4))),
assert_eq(first(l), 2),
assert_eq(last(l), list(2, 4)),
__builtin_print_catch(last("")),
__builtin_print_catch(first(list())),
__builtin_print_catch(last(list())),
__builtin_print_catch(first("")),
assert_eq(last("a"), first("a")),
assert_eq(last("a"), "a"),
