# TODO: increase n once possible (10k, 100k?)
n = 1000
with open("./tests/programs/lots_of_underscore_calls.re", "w") as f:
    f.write("# autogenerated file: see `lots_of_underscore_calls_generator.py`\n")
    f.write("print(\n" + "_(" * n + "\"hello world\"" + ")" * n + "\n)\n")
