# TODO: increase n once possible (10k, 100k?)
n = 2000
with open("./tests/programs/lots_of_underscore_calls.re", "w") as f:
    f.write("# autogenerated file: see `lots_of_underscore_calls_generator.py`\n")
    for _ in range(10):
        f.write("print(\n" + "_(" * n + "\"hello world\"" + ")" * n + "\n),\n")
