import sys

AUTOGENERATED = "# autogenerated file: see `testmaker.py`\n"

try:
    name = sys.argv[1]
    run_all = False
except IndexError:
    run_all = True

if run_all or name == "lots_of_underscore_calls":
    # TODO: increase n once possible (10k, 100k?)
    n = 2000
    with open("./tests/programs/lots_of_underscore_calls.re", "w") as f:
        f.write(AUTOGENERATED)
        for _ in range(10):
            f.write("print(\n" + "_(" * n + "\"hello world\"" + ")" * n + "\n),\n")

if run_all or name == "mass_assignment":
    n = 400_000
    with open("./tests/programs/mass_assignment.re", "w") as f:
        f.write(AUTOGENERATED)
        f.write("=(x0, \"hello, world!\"),\n")
        for i in range(n):
            f.write(f"=(x{i + 1}, x{i}),\n")
        f.write(f"assert_eq(x{n}, \"hello, world!\"),\n")
